name: Kustomize Diff

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run_and_post_diff:
    runs-on: ubuntu-latest
    env:
      SUBDIRECTORIES: |
        dev
        prod

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          sudo mv kustomize /usr/local/bin/

      - name: Run command in source branch
        run: |
          for dir in $SUBDIRECTORIES; do
            echo "Running command in $dir"
            /usr/local/bin/kustomize build ${dir} > $GITHUB_WORKSPACE/source_${dir}.txt
          done

      - name: Checkout destination code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Run command in destination branch
        run: |
          for dir in $SUBDIRECTORIES; do
            echo "Running command in $dir"
            /usr/local/bin/kustomize build ${dir} > $GITHUB_WORKSPACE/destination_${dir}.txt
          done

      - name: Generate diff and post as comment
        run: |
          for dir in $SUBDIRECTORIES; do
            diff=$(diff -u $GITHUB_WORKSPACE/source_${dir}.txt $GITHUB_WORKSPACE/destination_${dir}.txt) || true
            if [ -n "$diff" ]; then
              echo "#### Diff for $dir:" >> $GITHUB_WORKSPACE/diff.md
              echo "```diff" >> $GITHUB_WORKSPACE/diff.md
              echo "$diff" >> $GITHUB_WORKSPACE/diff.md
              echo "```\n" >> $GITHUB_WORKSPACE/diff.md
            fi
          done
          gh pr review --body-file $GITHUB_WORKSPACE/diff.md
          rm diff.md

      - name: Cleanup files
        run: |
          for dir in $SUBDIRECTORIES; do
            rm $GITHUB_WORKSPACE/source_${dir}.txt
            rm $GITHUB_WORKSPACE/destination_${dir}.txt
          done
