name: Kustomize Diff

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
        sudo mv kustomize /usr/local/bin

    - name: ls
      run: ls -al

    - name: Build and save output (PR branch)
      run: |
        for i in ${{ vars.SUBFOLDERS }}; do
          kustomize build $i > "pr_output_$i.txt"
        done

    - name: Checkout destination branch
      run: |
        git checkout ${{ github.base_ref }}

    - name: Build and save output (destination branch)
      run: |
        for i in ${{ vars.SUBFOLDERS }}; do
          kustomize build $i > "base_output_$i.txt"
        done

    - name: Switch back to PR branch
      run: |
        git checkout ${{ github.head_ref }}

    - name: Compare outputs and comment on PR
      run: |
        comment=""
        for i in ${{ vars.SUBFOLDERS }}; do
          if diff -q "pr_output_$i.txt" "base_output_$i.txt"; then
            comment+="No changes in the output of 'kustomize build' for folder $i.\n"
          else
            echo "Create output"
            diff_output=$(diff -u "pr_output_$i.txt" "base_output_$i.txt")
            comment+="There are differences in the output of 'kustomize build' for folder $i between the source and destination branches:\n\`\`\`diff\n$diff_output\n\`\`\`\n"
          fi
        done
        echo "$comment"
        echo "$comment" > comment.txt
        gh pr comment ${{ github.event.pull_request.number }} --body-file comment.txt
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
